### ISSUE TITLE
矩阵乘性能数据

### ISSUE THREAD

**Issue by yyfcc17** [bytedance/decoupleQ#10]
你好，请问有W4A16与FP16矩阵乘的具体性能对比数据吗？

**Comment by gavinchen430** [comment]
在A30上，m=1,n=16384,k=4096 FP16带宽大概750GB/s， W4A16大概是600GB/s。

**Comment by yyfcc17** [comment]
谢谢回复，请问具体的FP16矩阵乘和W4A16，W2A16矩阵乘，总体时间上加速如何呢？
